---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/19 16:48
---

require "Common/define"
require "Common/protocal"
require "Common/functions"
Event = require 'Logic/_Events'

require "3rd/pblua/login_pb"
require "3rd/pbc/protobuf"

local sproto = require "3rd/sproto/sproto"
local core = require "sproto.core"
local print_r = require "3rd/sproto/print_r"

GameNetwork = {};
local this = GameNetwork;

local transform;
local gameObject;
local islogging = false;

function GameNetwork.Start()
    logWarn("GameNetwork.Start!!");
    Event:AddEventListener(Protocal.Connect, this.OnConnect);
    Event:AddEventListener(Protocal.Message, this.OnMessage);
    Event:AddEventListener(Protocal.Exception, this.OnException);
    Event:AddEventListener(Protocal.Disconnect, this.OnDisconnect);
end
function GameNetwork.Self()
    return self
end

--Socket消息--
function GameNetwork.OnSocket(key, data)
    Event:Dispatcher(tostring(key), data);
end

--当连接建立时--
function GameNetwork.OnConnect()
    logWarn("Game Server connected!!");
end

--异常断线--
function GameNetwork.OnException()
    islogging = false;
    --NetManager:SendConnect();
    logError("OnException------->>>>");
end

--连接中断，或者被踢掉--
function GameNetwork.OnDisconnect()
    islogging = false;
    logError("OnDisconnect------->>>>");
end

--登录返回--
function GameNetwork.OnMessage(buffer)
    if TestProtoType == ProtocalType.BINARY then
        this.TestLoginBinary(buffer);
    end
    if TestProtoType == ProtocalType.PB_LUA then
        this.TestLoginPblua(buffer);
    end
    if TestProtoType == ProtocalType.PBC then
        this.TestLoginPbc(buffer);
    end
    if TestProtoType == ProtocalType.SPROTO then
        this.TestLoginSproto(buffer);
    end
    ----------------------------------------------------
    --local ctrl = CtrlManager.GetCtrl(CtrlNames.Message);
    --if ctrl ~= nil then
    --    ctrl:Awake();
    --end
    logWarn('OnMessage-------->>>');
end

--二进制登录--
function GameNetwork.TestLoginBinary(buffer)
    local protocal = buffer:ReadByte();
    local str = buffer:ReadString();
    log('TestLoginBinary: protocal:>'..protocal..' str:>'..str);
end

--PBLUA登录--
function GameNetwork.TestLoginPblua(buffer)
    local protocal = buffer:ReadByte();
    local data = buffer:ReadBuffer();

    local msg = login_pb.LoginResponse();
    msg:ParseFromString(data);
    log('TestLoginPblua: protocal:>'..protocal..' msg:>'..msg.id);
end

--PBC登录--
function GameNetwork.TestLoginPbc(buffer)
    local protocal = buffer:ReadByte();
    local data = buffer:ReadBuffer();

    local path = Util.DataPath.."lua/3rd/pbc/addressbook.pb";

    local addr = io.open(path, "rb")
    local buffer = addr:read "*a"
    addr:close()
    protobuf.register(buffer)
    local decode = protobuf.decode("tutorial.Person" , data)

    print(decode.name)
    print(decode.id)
    for _,v in ipairs(decode.phone) do
        print("\t"..v.number, v.type)
    end
    log('TestLoginPbc: protocal:>'..protocal);
end

--SPROTO登录--
function GameNetwork.TestLoginSproto(buffer)
    local protocal = buffer:ReadByte();
    local code = buffer:ReadBuffer();

    local sp = sproto.parse [[
    .Person {
        name 0 : string
        id 1 : integer
        email 2 : string

        .PhoneNumber {
            number 0 : string
            type 1 : integer
        }

        phone 3 : *PhoneNumber
    }

    .AddressBook {
        person 0 : *Person(id)
        others 1 : *Person
    }
    ]]
    local addr = sp:decode("AddressBook", code)
    print_r(addr)
    log('TestLoginSproto: protocal:>'..protocal);
end

--卸载网络监听--
function GameNetwork.Unload()
    Event:RemoveEventListeners(Protocal.Connect);
    Event:RemoveEventListeners(Protocal.Message);
    Event:RemoveEventListeners(Protocal.Exception);
    Event:RemoveEventListeners(Protocal.Disconnect);
    logWarn('Unload GameNetwork...');
end