---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/21 13:16
---

--//测试获得数字电视的键值映射：
--方向键：
--上：      KeyCode.UpArrow
--下：      KeyCode.DownArrow
--左：      KeyCode.LeftArrow
--右：      KeyCode.RightArrow
--
--功能键：
--OK键：    KeyCode.JoystickButton0(小米盒子比较特殊，键值为：KeyCode MIOkKeyCode = (KeyCode)10;)
--返回键：  KeyCode.Escape
--菜单键：  KeyCode.Menu
--
-----------------------
--作者：Mr_厚厚
--来源：CSDN
--原文：https://blog.csdn.net/cordova/article/details/51036547
--版权声明：本文为博主原创文章，转载请附上博文链接！

--local socket = require "socket"
--local start_time = socket.gettime()
--local end_time= socket.gettime()
--local use_time = (end_time - start_time )*1000
--print("used time: "..use_time .."ms \n")
TV_KeyCode = {}
local this = TV_KeyCode
--枚举
local key = UnityEngine.KeyCode
--按钮点击方法
local KeyFunc=UnityEngine.Input.GetKeyDown
--Unity 时间类
local Time=UnityEngine.Time
--当前按钮,点击上下左右会获取不同的按钮或执行里面的函数,所以东西都封装在BaseBttn中
this.CurrentTable = nil
--上按钮
local UpArrow = key.UpArrow
--下按钮
local DownArrow = key.DownArrow
--左按钮
local LeftArrow = key.LeftArrow
--右按钮
local RightArrow = key.RightArrow
--确定按钮
local Ok = key.JoystickButton0 or 10
--测试ok键用键盘Enter键
--local Ok =key.Return
--退出按钮
local Escape = key.Escape
--菜单按钮
local Menu = key.Menu
--帧检测事件
local UpdateHandle=nil
--当前时间
local currentTime=0
--上键最后点击时间
local upArrowLastTime=0
--退出最后点击时间
local EscapeLastTime=0
--判断双击的时间间隔
local TimeInterval=0.2
--开始按键检测
function TV_KeyCode.StartKeyTesting()
    --推荐使用这种Update方法
    UpdateHandle=UpdateBeat:CreateListener(this.KeyCode,self)
    UpdateBeat:AddListener(UpdateHandle)
end
--移除按键检测
function TV_KeyCode.RemoveKeyTesting()
    UpdateBeat:RemoveListener(UpdateHandle)
end
--Update方法
function TV_KeyCode.KeyCode()
    if KeyFunc(UpArrow) then
        if  this.CurrentTable then
            this.CurrentTable:UpBtn()
        end
        --当前程序运行时间
        currentTime =Time.realtimeSinceStartup
        --是否双击
        if currentTime-upArrowLastTime<TimeInterval then
            --log("上键双击")
        end
        --重新赋值
        upArrowLastTime=Time.realtimeSinceStartup
    elseif KeyFunc(DownArrow) then
        --log("下键")
        if  this.CurrentTable then
            this.CurrentTable:DownBtn()
        end
    elseif KeyFunc(LeftArrow) then
        --log("左键")
        if  this.CurrentTable then
            this.CurrentTable:LeftBtn()
        end
    elseif KeyFunc(RightArrow) then
            --log("右键")
        if  this.CurrentTable then
            this.CurrentTable:RightBtn()
        end
    elseif KeyFunc(Ok) then
            --log("OK键")
        if  this.CurrentTable then
            this.CurrentTable:SetOk()
        end
    elseif KeyFunc(Escape) then
            currentTime =Time.realtimeSinceStartup
            if currentTime-EscapeLastTime<TimeInterval then
                --log("退出双击")
            else
                --log("退出单击")
            end
            EscapeLastTime=Time.realtimeSinceStartup
    --elseif KeyFunc(Menu) then
    --        log("菜单键")
    end
end


