---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/17 9:36
---
BasePlayerInfo={}
local this=BasePlayerInfo
--按钮类
function BasePlayerInfo:New(go)
    local NewPlayerInfo={}
    setmetatable(NewPlayerInfo,{__index=self})
    NewPlayerInfo.gameObject=go.gameObject
    return NewPlayerInfo
end

function BasePlayerInfo:PlayForward()
    self:SetGo(true)
    self.gameObject:GetComponent("TweenPosition"):PlayForward()
end
function BasePlayerInfo:PlayReverse()
    self:SetGo(false)
    self.gameObject:GetComponent("TweenPosition"):PlayReverse()
end
function BasePlayerInfo:SetInfo(url,name,level,experience,pos)
    self:SetGo(true)
    local obj=self.gameObject.transform:Find("PlayerInfo")
    obj.transform.localPosition=pos
    obj.transform:Find("Name"):GetComponent("UILabel").text="[b]"..name
    obj.transform:Find("Level"):GetComponent("UILabel").text="[b]"..level
    obj.transform:Find("Experience"):GetComponent("UILabel").text="[b]"..experience
    setWeChatHead:SetAsyncImage(url,obj.transform:Find("head"):GetComponent("UITexture"))
end
function BasePlayerInfo:SetGo(isTrue)
    self.gameObject:SetActive(isTrue)
end
function BasePlayerInfo:SetPaoFen(xiaPao)
    local obj=self.gameObject.transform:Find("PlayerInfo/paofen")
    if xiaPao=="guo" then
        obj.gameObject:SetActive(false)
    elseif xiaPao=="yi"  then
        obj:GetComponent("UISprite").spriteName="1fen"
        obj.gameObject:SetActive(true)
    elseif xiaPao=="er"  then
        obj:GetComponent("UISprite").spriteName="2fen"
        obj.gameObject:SetActive(true)
    elseif xiaPao=="san"  then
        obj:GetComponent("UISprite").spriteName="3fen"
        obj.gameObject:SetActive(true)
    end

end