---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/18 10:01
---
BaseOtherHnad={}
local this=BaseOtherHnad

--按钮类
function BaseOtherHnad:New(go,pengPrefabPoolName,ChuPaiPrefabPoolName,pengAddx,pengAddy,isDepthAdd,RotationZ)
    local NewButton={}
    setmetatable(NewButton,{__index=self})

    NewButton.gameObject=go.gameObject
    NewButton.parent=go.transform.parent
    NewButton.CurrentDaChuObj=nil
    NewButton.ChuObj=nil
    NewButton.id=nil
    --打出牌动画
    NewButton.DaPaiAnimation=NewButton.parent.transform:Find("DaAnimation")
    NewButton.DaChu=NewButton.parent.transform:Find("Chu")
    NewButton.PengChu=NewButton.parent.transform:Find("ChiPeng")
    NewButton.Anims=NewButton.parent.transform:Find("Anims")
    NewButton.Depth=isDepthAdd and 1 or 100
    NewButton.isDepthAdd=isDepthAdd
    NewButton.pengAddx=pengAddx
    NewButton.pengAddy=pengAddy
    NewButton.RotationZ=RotationZ
    --NewButton.ChuPos=
    NewButton.pengPrefabPoolName=pengPrefabPoolName
    NewButton.ChuPaiPrefabPoolName=ChuPaiPrefabPoolName
    NewButton.Staet={
        none=0,
        mo=1,
        peng=2,
        gang=3
    }
    NewButton.CurrentStaet=NewButton.Staet.none
    return NewButton
end
--显示手牌
function BaseOtherHnad:ShowHand()
    self.gameObject:SetActive(true)
end
--摸牌
function BaseOtherHnad:MoPai()
    self.CurrentStaet=self.Staet.mo
    self.gameObject.transform:GetChild(13).gameObject:SetActive(true)
end
--打牌
function BaseOtherHnad:DaPai(data)
    self.gameObject.transform:GetChild(13).gameObject:SetActive(false)
    --碰的状态下打牌会在碰后少一张手牌
    if self.CurrentStaet==self.Staet.peng then
         self:RemovePaiCount(1)
    end
    self:ShowAnimation(data)
    self.CurrentStaet=self.Staet.none

end
--减少手牌数量
function BaseOtherHnad:RemovePaiCount(num)
    local x=0
    for i=1,self.gameObject.transform.childCount,1 do
        --得到子物体第一个显示的手牌下标
        local obj= self.gameObject.transform:GetChild(i-1).gameObject
        if obj.activeSelf then
            obj:SetActive(false)
            x=x+1
        end
        if x==num then
            break
        end
    end
end
function BaseOtherHnad:Peng(data,actionPlayerId)
    self.CurrentStaet=self.Staet.peng
    --减少两张牌
    self:RemovePaiCount(2)
    self:ShowPenngAnimation("peng")
    --显示碰牌
     self:ShowPeng(data)
    StartGame.HuiShowChu(actionPlayerId)
end
function BaseOtherHnad:Gane(id,data)
    self.CurrentStaet=self.Staet.gang
    if not id then
        self:RemovePaiCount(4)
    else
        self:RemovePaiCount(3)
        StartGame.HuiShowChu(id)
    end
    self:ShowPenngAnimation("gang")
    --显示杠牌
    self:MoPai()
    self:ShowGang(data)
end
function BaseOtherHnad:Hu()
    self:ShowPenngAnimation("hu")
end
function BaseOtherHnad:HandPlayerAction(data)
    if data.type=="da" then
        self:DaPai("m"..data.pai)
    elseif data.type=="peng" then
        self:Peng("m"..data.pai,data.dachupaiPlayerId)
    elseif data.type=="gang" then
        if data.dachupaiPlayerId then
            self:Gane(data.dachupaiPlayerId,"m"..data.pai)
        else
            self:Gane(nil,"m"..data.pai)
        end
    elseif data.type=="hu" then
        self:Hu()
    elseif data.type=="mo" then
        self:MoPai()
    end
end
--显示打牌动画
function BaseOtherHnad:ShowAnimation(data)
    local f= coroutine.create(function ()
        self.DaPaiAnimation.gameObject:SetActive(true)
        self.DaPaiAnimation.transform:Find("Sprite"):GetComponent("UISprite").spriteName=data
        self.DaPaiAnimation:GetComponent("TweenScale"):PlayForward()
        coroutine.wait(0.5)
        self.DaPaiAnimation.gameObject:SetActive(false)
        self:ShowDaChuCard(data)
    end)
    coroutine.resume(f)
end
--显示吃碰杠动画
function BaseOtherHnad:ShowPenngAnimation(name)
    self.Anims:GetComponent("PlayAnimation"):PlayAnimationByName(name)
end
--显示打出的牌
function BaseOtherHnad:ShowDaChuCard(data)
    local obj= BaseHelper.SetObj(self.ChuPaiPrefabPoolName,self.DaChu,nil,nil)
    self.ChuObj=obj
    obj.transform:Find("Sprite"):GetComponent("UISprite").spriteName=data
    obj.transform.localRotation=UnityEngine.Quaternion.Euler(0,0,self.RotationZ)
    if  self.isDepthAdd then
        obj.transform:Find("Sprite"):GetComponent("UISprite").depth=self.Depth+2
        obj:GetComponent("UISprite").depth=self.Depth+1
        self.Depth=self.Depth+2
    else
        obj.transform:Find("Sprite"):GetComponent("UISprite").depth=self.Depth-1
        obj:GetComponent("UISprite").depth=self.Depth-2
        self.Depth=self.Depth-2
    end
    self.DaChu:GetComponent("UIGrid"):Reposition()
end
--回收打出的牌
function BaseOtherHnad:HuiShouPai()
    objPoolMgr:Release(self.ChuPaiPrefabPoolName,self.ChuObj)
end
--显示碰
function BaseOtherHnad:ShowPeng(data)
    local obj=objPoolMgr:Get(self.pengPrefabPoolName)
    --obj.transform.localScale=Vector3.zero
    obj.transform:SetParent(self.PengChu)
    obj.transform:GetChild(3).gameObject:SetActive(false)
    obj.transform:GetChild(0):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(1):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(2):GetChild(0):GetComponent("UISprite").spriteName=data
    local x=self.PengChu.transform.childCount-1
    obj.transform.localPosition=Vector3.New(x*self.pengAddx,x*self.pengAddy,0)
end
--显示杠
function BaseOtherHnad:ShowGang(data)
    for i=1, self.PengChu.transform.childCount,1 do
        local obj=self.PengChu.transform:GetChild(i-1)
        if obj:GetChild(0):GetChild(0):GetComponent("UISprite").spriteName==data then
            obj.transform:GetChild(3):GetChild(0):GetComponent("UISprite").spriteName=data
            obj.transform:GetChild(3).gameObject:SetActive(true)
            return nil
        end
    end
    local obj=objPoolMgr:Get(self.pengPrefabPoolName)
    obj.transform:SetParent(self.PengChu)
    obj.transform:GetChild(0):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(1):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(2):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(3):GetChild(0):GetComponent("UISprite").spriteName=data
    obj.transform:GetChild(3).gameObject:SetActive(true)
    local x=self.PengChu.transform.childCount-1
    obj.transform.localPosition=Vector3.New(x*self.pengAddx,x*self.pengAddy,0)
end

--对象池回收打出牌
function BaseOtherHnad:HuiShouDaChu()
    for i=1, self.DaChu.transform.childCount,1 do
        objPoolMgr:Release(self.ChuPaiPrefabPoolName,self.DaChu.transform:GetChild(i-1).gameObject)
    end
end

--对象池回收吃碰
function BaseOtherHnad:HuiShouChiPeng()
    for i=1, self.PengChu.transform.childCount,1 do
        objPoolMgr:Release(self.pengPrefabPoolName,self.PengChu.transform:GetChild(i-1).gameObject)
    end
end
--显示panforme的动作
function  BaseOtherHnad:ShowPanForMeAction(data)
    if data.type=="peng" then
        self:ShowPenngAnimation("peng")
    elseif data.type=="gang" then
        self:ShowPenngAnimation("gang")
    elseif data.type=="hu" then
        self:ShowPenngAnimation("hu")
    end
end
