---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:17
---
-----------------帮助方法类,一些通用的方法
BaseHelper={}
local this=BaseHelper

---生成预制体,obj=预制体,parent=父物体,pos=位置,scal=大小
function BaseHelper.CreateObj(obj,parent,pos,scal)
    local go=GameObject.Instantiate(obj)
    if parent then
        go.transform:SetParent(parent.transform)
    end
    if pos then
        go.transform.localPosition=pos
    end
    if scal then
        go.transform.localScale=scal
    end
    return go
end

---对象池,obj=预制体,parent=父物体,pos=位置,scal=大小
function BaseHelper.SetObj(PoolName,parent,pos,scal,rotation)
    local go=objPoolMgr:Get(PoolName)
    if parent then
        go.transform:SetParent(parent.transform)
    end
    if pos then
        go.transform.localPosition=pos
    end
    if scal then
        go.transform.localScale=scal
    end
    return go
end

--按钮声音播放,所有的声音都打包在sound.unity3d ab包中
function BaseHelper.PlaySound(asertname)
    soundMgr:PlaySound("sound",asertname)
end

--数字图片 三位数
function BaseHelper.SetImageNumber(num,go,str)
    local ge=num%10
    local shi=math.modf(num/10)%10
    local bai=math.modf(num/100)
    local One=go.transform:GetChild(0):GetComponent("UISprite")
    local Two=go.transform:GetChild(1):GetComponent("UISprite")
    local Three=go.transform:GetChild(2):GetComponent("UISprite")
    if bai~=0 then
        --One.gameObject:SetActive(true)
        --Two.gameObject:SetActive(true)
        --Three.gameObject:SetActive(true)
        One.spriteName=bai..str
        Two.spriteName=shi..str
        Three.spriteName=ge..str
    elseif shi~=0 then
        --One.gameObject:SetActive(false)
        --Two.gameObject:SetActive(true)
        --Three.gameObject:SetActive(true)
        Two.spriteName=shi..str
        Three.spriteName=ge..str
    else
        --One.gameObject:SetActive(false)
        --Two.gameObject:SetActive(false)
        --Three.gameObject:SetActive(true)
        Three.spriteName=ge..str
    end
end