---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/17 17:36
---
Http_Helper={}
local this=Http_Helper
local UnityWebRequest=UnityEngine.Networking.UnityWebRequest
local UploadHandlerRaw=UnityEngine.Networking.UploadHandlerRaw
local DownloadHandlerBuffer=UnityEngine.Networking.DownloadHandlerBuffer
--url 网址,func 回调函数,titleFunc 错误提示函数  timeout   http 最大连接时间 ,超过则失败
function Http_Helper.WebRequestText(url ,func)
    local ff=coroutine.create(function ()
        local web=UnityWebRequest.Get(url)
        --设置超时时间
        web.timeout=2
        coroutine.www(web:Send())
        if web.isError then
            if web.error=="Request timeout" then
                log(web.error)
                --this.WebRequestText(url,func)
                --return 0
            end
        elseif web.responseCode:equals(200) then
            if func then
                func(web.downloadHandler)
            end
        else
            log(web.downloadHandler.text)
        end
    end)
    coroutine.resume(ff)
end
----- 通过http传递json  需要传递json的http比较特殊,不能直接发送
function Http_Helper.WebRequestByJsonText(url ,Json,func)
    local ff=coroutine.create(function ()
        log(url)
        local web =UnityWebRequest.New(url,"POST")
        local  bodyRaw = AppConst.GetByte(Json)
        web.uploadHandler =UploadHandlerRaw.New(bodyRaw)
        web.downloadHandler =DownloadHandlerBuffer.New();
        web:SetRequestHeader("Content-Type", "application/json")
        --设置超时时间
        web.timeout=2
        coroutine.www(web:Send())
        if web.isError then
            if web.error=="Request timeout" then
                log(web.error)
                --this.WebRequestText(url,func)
                --return 0
            end
        elseif web.responseCode:equals(200) then
            if func then
                func(web.downloadHandler)
            end
        else
            log(web.downloadHandler.text)
        end
    end)
    coroutine.resume(ff)
end

----url 网址,func 回调函数,titleFunc 错误提示函数  timeout   http 最大连接时间 ,超过则失败
--function Http_Helper.WebRequestText(url ,func,titleFunc,timeout)
--    local ff=coroutine.create(function ()
--        local web=UnityWebRequest.Get(url)
--        --设置超时时间
--        if timeout then
--            web.timeout=timeout
--        else
--            web.timeout=2
--        end
--        coroutine.www(web:Send())
--        if web.isError then
--            if web.error=="Request timeout" then
--                if titleFunc then
--                    titleFunc("网络波动,连接时间过长,正在重连")
--                end
--                this.WebRequestText(url,func,titleFunc)
--                return 0
--            else
--                if titleFunc then
--                    titleFunc("网络错误,请重试")
--                end
--            end
--            log(web.error)
--        elseif web.responseCode:equals(200) then
--            if func then
--                func(web.downloadHandler)
--            end
--        else
--            log(web.downloadHandler.text)
--        end
--    end)
--    coroutine.resume(ff)
--end



