---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/28 14:32
---
GameExpressioAndWittyPanel={}
local this=GameExpressioAndWittyPanel
local gameobject
local transform
function  GameExpressioAndWittyPanel.Awake(obj)
    logWarn("GameExpressioAndWittyPanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
end
function  GameExpressioAndWittyPanel.Start()
    logWarn("GameExpressioAndWittyPanel.Satrt--->>");
end
