---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/28 14:26
---
GamePanel={}
local this=GamePanel
local gameobject
local transform
function  GamePanel.Awake(obj)
    logWarn("GamePanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
    this.InitPanel()
end
function  GamePanel.Start()
    logWarn("GamePanel.Satrt--->>");
end

function GamePanel.InitPanel()
    --返回大厅
    this.Return=transform:Find("YouXiWai/CenterAnchor/fanhuidating")
    this.MoreSetting=transform:Find("YouXiWai/TopRightAnchor/shezhi")
    this.TuoGuan=transform:Find("YouXiWai/TopRightAnchor/tuoguan")
    this.TuiChu=transform:Find("YouXiWai/TopRightAnchor/tuichu")

    --头像
    this.MInfo= transform:Find("MyPosition/HeadPosition")
    this.RInfo=transform:Find("RightPosition/HeadPosition")
    this.LInfo=transform:Find("LeftPosition/HeadPosition")
    this.TInfo=transform:Find("TopPosition/HeadPosition")

    --手牌
    this.MHand= transform:Find("MyPosition/Hand")
    this.RHand=transform:Find("RightPosition/Hand")
    this.LHand=transform:Find("LeftPosition/Hand")
    this.THand=transform:Find("TopPosition/Hand")

    --打出牌
    this.MChu= transform:Find("MyPosition/Chu")
    this.RChu=transform:Find("RightPosition/Chu")
    this.LChu=transform:Find("LeftPosition/Chu")
    this.TChu=transform:Find("TopPosition/Chu")
    --碰牌
    this.MPeng= transform:Find("MyPosition/ChiPeng")
    this.RPeng=transform:Find("RightPosition/ChiPeng")
    this.LPeng=transform:Find("LeftPosition/ChiPeng")
    this.TPeng=transform:Find("TopPosition/ChiPeng")
    --个人碰杠动画
    this.MoAnimation=transform:Find("MyPosition/Anims"):GetComponent("PlayAnimation")
    --个人打牌动画
    this.MDaAnimation=transform:Find("MyPosition/DaAnimation")

    --操作显示
    this.Options=transform:Find("YouXiWai/options")

    this.huOptions=transform:Find("YouXiWai/options/hu")
    this.gangOptions=transform:Find("YouXiWai/options/gang")
    this.pengOptions=transform:Find("YouXiWai/options/peng")
    this.quxiaoOptions=transform:Find("YouXiWai/options/quxiao")

    --下跑
    this.XiaPao=transform:Find("YouXiWai/XuanZePaoFen")
    this.XiaPaoOne=transform:Find("YouXiWai/XuanZePaoFen/yi")
    this.XiaPaoTwo=transform:Find("YouXiWai/XuanZePaoFen/er")
    this.XiaPaoThree=transform:Find("YouXiWai/XuanZePaoFen/san")
    this.XiaPaoCancle=transform:Find("YouXiWai/XuanZePaoFen/guo")
    --时间
    this.Time=transform:Find("Time")
    this.Liang=transform:Find("Time/Liang")
    this.Di=transform:Find("Time/Di")

    --
    this.CenterAnchor=transform:Find("YouXiWai/CenterAnchor")
    this.zhunbei=transform:Find("YouXiWai/CenterAnchor/zhunbei")
    this.jishiq=transform:Find("YouXiWai/CenterAnchor/jishiqi"):GetComponent("UILabel")
    this.fanhuidating=transform:Find("YouXiWai/CenterAnchor/fanhuidating")
    this.duijukaishi=transform:Find("YouXiWai/CenterAnchor/duijukaishi")
    --右上
    this.SheZhi=transform:Find("YouXiWai/TopRightAnchor/SheZhiParent/shezhi")
    this.tuoguan=transform:Find("YouXiWai/TopRightAnchor/SheZhiParent/tuoguan")
    this.tuichu=transform:Find("YouXiWai/TopRightAnchor/SheZhiParent/tuichu")
    this.TuoGuanBg=transform:Find("YouXiWai/TuoGuan")
    this.CancleTuoGuanBtn=transform:Find("YouXiWai/TuoGuan/TuiChuTuoGuanButton")
    --左上角
    this.TopLeftAnchor=transform:Find("YouXiWai/TopLeftAnchor")
    this.TopHunPai=transform:Find("YouXiWai/TopLeftAnchor/HunZiPaiParent/caishenpai/caishenpaisp"):GetComponent("UISprite")
    this.ShengYuCount=transform:Find("YouXiWai/TopLeftAnchor/HunZiPaiParent/shengyupai/shengyulabel"):GetComponent("UILabel")
end

