---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/28 14:31
---

GameMoreSettingPanel={}
local this=GameMoreSettingPanel
local gameobject
local transform
function  GameMoreSettingPanel.Awake()
    logWarn("GameMoreSettingPanel.Awake--->>");
    gameobject="更多设置"
    transform=gameobject.transform
    this.InitView()
end
function  GameMoreSettingPanel.Start()
    logWarn("GameMoreSettingPanel.Satrt--->>");
end

function GameMoreSettingPanel.InitView()
    this.Setting="设置"
    this.Trusteeship="托管"
    this.Retuan="退出"
end