---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:54
---

local gameobject
local transform
QianDaoPanel={}
local this=QianDaoPanel
function  QianDaoPanel.Awake(obj)
    logWarn("QianDaoPanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
    this.InitPanel()
end
function  QianDaoPanel.Start()
    logWarn("QianDaoPanel.Satrt--->>");
end

function  QianDaoPanel.InitPanel()
    this.Return=transform:Find("MainInfoBg/ReturnBtn")
    this.LianXuNum=transform:Find("MainInfoBg/DayNumberLabel"):GetComponent("UILabel")
end
