---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:54
---

local gameobject
local transform
RecordPanel={}
local this=RecordPanel
function  RecordPanel.Awake(obj)
    logWarn("RecordPanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
    this.InitPanel()
end
function  RecordPanel.Start()
    logWarn("RecordPanel.Satrt--->>");
end

function RecordPanel.InitPanel()
    this.LeftGrid=transform:Find("Main/LeftBg/View/Grid")
    this.Return=transform:Find("Main/Record")
    this.Title=transform:Find("Main/Title")
end

