---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:54
---

local gameobject
local transform
RulePanel={}
local this=RulePanel
function  RulePanel.Awake(obj)
    logWarn("RulePanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
    this.InitPanel()
end
function  RulePanel.Start()
    logWarn("RulePanel.Satrt--->>");
end

function RulePanel.InitPanel()
    this.BaseRule=transform:Find("MainInfo/BaseRecord")
    this.MultiplicationRule=transform:Find("MainInfo/SaunFanRecord")

    this.BaseRuleGo=transform:Find("MainInfo/BaseRule")
    this.MultiplicationRuleGo=transform:Find("MainInfo/SuanFenRule")

    this.BaseRuleGoSlider=transform:Find("MainInfo/BaseRule/UiSprite")
    this.MultiplicationRuleGoSlider=transform:Find("MainInfo/SuanFenRule/UiSprite")

    this.Return=transform:Find("MainInfo/ReturnBtn")
end
