---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:54
---

local gameobject
local transform
SettingPanel={}
local this=SettingPanel
function  SettingPanel.Awake(obj)
    logWarn("SignInPanel.Awake--->>");
    gameobject=obj
    transform=obj.transform
    this.InitPanel()
end
function  SettingPanel.Start()
    logWarn("SettingPanel.Satrt--->>");
end

function  SettingPanel.InitPanel()
    this.BgSet=transform:Find("MainInfo/BGLabel")
    this.BgStart=transform:Find("MainInfo/BGStart")
    this.BGClose=transform:Find("MainInfo/BGClose")

    this.EffectSet=transform:Find("MainInfo/EffectLabel")
    this.EffectStart=transform:Find("MainInfo/EffectStart")
    this.EtffecClose=transform:Find("MainInfo/EtffecClose")


    this.Return=transform:Find("MainInfo/ReturnBtn")
end
