//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DaTingSocketWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DaTingSocket), typeof(Manager));
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("MIsStartSocket", get_MIsStartSocket, set_MIsStartSocket);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DaTingSocket obj = (DaTingSocket)ToLua.CheckObject<DaTingSocket>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SendMsg(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MIsStartSocket(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DaTingSocket obj = (DaTingSocket)o;
			bool ret = obj.MIsStartSocket;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MIsStartSocket on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MIsStartSocket(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DaTingSocket obj = (DaTingSocket)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.MIsStartSocket = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MIsStartSocket on a nil value");
		}
	}
}

