//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SetWechatHeadWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SetWechatHead), typeof(Manager));
		L.RegFunction("Init", Init);
		L.RegFunction("ClearImageCache", ClearImageCache);
		L.RegFunction("SetAsyncImage", SetAsyncImage);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("path", get_path, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SetWechatHead obj = (SetWechatHead)ToLua.CheckObject<SetWechatHead>(L, 1);
			bool o = obj.Init();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearImageCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SetWechatHead obj = (SetWechatHead)ToLua.CheckObject<SetWechatHead>(L, 1);
			obj.ClearImageCache();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAsyncImage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				SetWechatHead obj = (SetWechatHead)ToLua.CheckObject<SetWechatHead>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.SetAsyncImage(arg0);
				return 0;
			}
			else if (count == 3)
			{
				SetWechatHead obj = (SetWechatHead)ToLua.CheckObject<SetWechatHead>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UITexture arg1 = (UITexture)ToLua.CheckObject<UITexture>(L, 3);
				obj.SetAsyncImage(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SetWechatHead.SetAsyncImage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_path(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SetWechatHead obj = (SetWechatHead)o;
			string ret = obj.path;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index path on a nil value");
		}
	}
}

