---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/28 14:32
---


GameExpressioAndWittyCtrl={}
local this=GameExpressioAndWittyCtrl
local gameobject
local transform

function GameExpressioAndWittyCtrl.New()
    logWarn("GameExpressioAndWittyCtrl.New--->>");
    return this;
end

function GameExpressioAndWittyCtrl.OnCreate(obj)
    gameobject=obj
    transform=obj.transform
end
