---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/28 14:30
---
--游戏中的更多按钮不需要通过c#生成
GameMoreSettingCtrl={}
local this=GameMoreSettingCtrl

local gameobject
local transform

local isShow=false

function GameMoreSettingCtrl.New()
    logWarn("GameMoreSettingCtrl.New--->>");
    return this;
end

function GameMoreSettingCtrl.Awake()
    GameMoreSettingPanel.Awake()
    this.OnCreate(GameMoreSettingPanel.gameobject)
end
--
function GameMoreSettingCtrl.OnCreate(obj)
    gameobject=obj
    transform=obj.transform
    --如果第一次则播放显示,否则播放隐藏
    --Todo 播放动画
    if isShow then
        --播放隐藏动画 并退出
        isShow=false
        return 0
    end
    --创建表
    --设置表关系
    --设置函数
    --设置初始表
    this.CreateTable()
    this.SetTable()
    this.SetOkFunc()
end

--创建表,共三个
function GameMoreSettingCtrl.CreateTable()
    --设置
    this.SettingBtn=ButtonBase:New(GameMoreSettingPanel.Setting)
    --托管
    this.TrusteeshipBtn=ButtonBase:New(GameMoreSettingPanel.Trusteeship)
    --返回
    this.ReturnBtn=ButtonBase:New(GameMoreSettingPanel.Retuan)
end


--设置表关系
function GameMoreSettingCtrl.CreateTable()
    --设置
    this.SettingBtn:SetAllTable(nil,nil,GameCtrl.MoreSettingBtn,this.TrusteeshipBtn)
    --托管
    this.TrusteeshipBtn:SetAllTable(nil,nil,this.SettingBtn,this.ReturnBtn)
    --返回
    this.ReturnBtn:SetAllTable(nil,nil,this.TrusteeshipBtn,nil)
end
--设置Ok按钮函数
function GameMoreSettingCtrl.CreateTable()
    --设置
    this.SettingBtn.okFunc=function()
        SettingCtrl.Awake()
    end
    --托管
    this.TrusteeshipBtn.okFunc=function()
        --TODO 托管
    end
    --返回
    this.ReturnBtn.okFunc=function()
        --todo 返回大厅
    end
end