---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:53
---
------------------------------------------字段以及表-----------------------------------------------------------------------------------
local gameobject
local transform
local cjson= require "cjson"
QianDaoCtrl={}
local this=QianDaoCtrl
local DayObj=nil

local GetQianDaoInfoUrl="/app/sgw/sign/listSignInfo"
local QianDaoUrl="/app/sgw/sign/userSign"
-----------------------------------------------初始化方法-----------------------------------------------------------------------------------
function QianDaoCtrl.New()
    logWarn("QianDaoCtrl.New--->>");
    return this;
end

function  QianDaoCtrl.Awake()
    logWarn("QianDaoCtrl.Awake--->>");
    panelMgr:CreatePanel('QianDao', this.OnCreate);
end

function QianDaoCtrl.OnCreate(obj)
    gameobject=obj
    transform=obj.transform
    this.GetDataFormService()
end
---------------------------------向服务器请求协议-----------------------------------------------------------------------------------------
---拉取签到信息
function QianDaoCtrl.GetDataFormService()
    local url=LocalHallHttpPort..GetQianDaoInfoUrl.."?token="..PlayerInfo.GameToken.."&member="..PlayerInfo.MemberId
    log("获取签到信息"..url)
    Http_Helper.WebRequestText(url,this.InitUI)
end

--签到获取经验值
function QianDaoCtrl.QianDaoByService()
    local url=LocalHallHttpPort..QianDaoUrl.."?token="..PlayerInfo.GameToken.."&member="..PlayerInfo.MemberId
    log("签到"..url)
    Http_Helper.WebRequestText(url,this.QianDaoResponse)
end
--------------------------------------请求回调以及数据处理------------------------------------------------------------------------------------
--拉取签到信息回调
function QianDaoCtrl.InitUI(data)
    log(data.text)
    local Jsondata=cjson.decode(data.text)
    if Jsondata.success then
        QianDaoPanel.LianXuNum.text="[b]"..Jsondata.data.signNum
        for i,v in pairs(Jsondata.data.signListVO) do
            if v then
                this.SetDayInfo(transform:Find("MainInfoBg").transform:GetChild(i+1):Find("ExperienceBg"),v.prizeNum,v.today,v.sign)
            end
        end
    else
        log("获取签到数据出错"..Jsondata.msg)
    end
end

--签到回调
function QianDaoCtrl.QianDaoResponse(data)
    log(data.text)
    local Jsondata=cjson.decode(data.text)
    if Jsondata.success then
        DayObj.transform:Find("HaveGet").gameObject:SetActive(true)
        --TODO 给出提示列表
        --CtrlManager.GetCtrl(CtrlNames.Message).GetExe()
        this.Close()
        --更新数据
        CtrlManager.GetCtrl(CtrlNames.SignIn).GetInfoFromService()
    else
        log("获取签到数据出错"..Jsondata.msg)
    end
end
--------------------------------内部函数------------------------------------------------------------------------------------------------
--设置签到天数的具体赋值
function QianDaoCtrl.SetDayInfo(go,prizeNum,today,sign)
    BaseHelper.SetImageNumber(prizeNum,go,"@2x")
    if today then
        DayObj=go.parent.gameObject
        this.CreateBtn()
        this.SetFirstBtn()
        --如果已经签过到则不必调用okFunc函数
        if sign then
            this.DayBtn.okFunc=nil
        end
    end
    if sign then
        go.parent:Find("HaveGet").gameObject:SetActive(true)
    end
end
function QianDaoCtrl.CreateBtn()
    -- 天数为服务器需要签到的天数
    this.DayBtn=ButtonBase:New(DayObj)
    --返回
    this.ReturnBtn=ButtonBase:New(QianDaoPanel.Return)
    ----设置左右上下表,
    this.SetTable()
    --设置确定函数
    this.SetSettingBtnOkFun()
end
function QianDaoCtrl.SetTable()
    this.DayBtn:SetDown(this.ReturnBtn)
    this.ReturnBtn:SetUp(this.DayBtn)
end

function QianDaoCtrl.SetSettingBtnOkFun()
    this.DayBtn.okFunc=function()
        -- 获取经验值
        this.QianDaoByService()
    end
    this.ReturnBtn.okFunc=function()
        this.DayBtn=nil
        this.ReturnBtn=nil
        this.Close()
        gameobject=nil
        transform=nil
        DayObj=nil
        CtrlManager.GetCtrl(CtrlNames.SignIn).SetFirstBtn()
    end
end
--设置初始按钮
function QianDaoCtrl.SetFirstBtn()
    this.DayBtn:SetStart()
end

--关闭事件--
function QianDaoCtrl.Close()
    panelMgr:ClosePanel(CloseNames.QianDao);
end
