---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:53
---
local gameobject
local transform
RecordCtrl={}
local this=RecordCtrl


-----------这里对象池的使用对于性能并无太大差别
--具体信息对象池
local ObjPoolItemName="Record"
--战绩左侧对象池
local ObjPoolRecordLeft="RecordLeft"
---lubehaviour
local  RecordLuaBehaviour=nil

local mJianGe=102
local mLittlePos=40
----利用表保存,战绩
this.RecordTabele={}
----战绩详情
this.RecordInfo={}
--要查看战绩索引
this.Index=1
--向下位置索引
--战绩数量
this.AllChildNum=0
--服务器将所有战绩信息传来
this.AllRecordInfo=nil

function RecordCtrl.New()
    logWarn("RecordCtrl.New--->>");
    return this;
end

function  RecordCtrl.Awake()
    logWarn("RecordCtrl.Awake--->>");
    panelMgr:CreatePanel('Record', this.OnCreate);
end

function RecordCtrl.OnCreate(obj)
    gameobject=obj
    transform=obj.transform
    RecordLuaBehaviour=obj:GetComponent("LuaBehaviour")
    this.LoadAssert()
    this.GetRecordByService()
end
--todo 获取对象,创建对象池
function RecordCtrl.LoadAssert()
    this.RecordItem=RecordLuaBehaviour:LoadAsset("RecordItem")
    this.RecordLeft=RecordLuaBehaviour:LoadAsset("RecordLeft")
    objPoolMgr:CreatePool(ObjPoolRecordLeft,30,30,this.RecordLeft)
    objPoolMgr:CreatePool(ObjPoolItemName,4,4,this.RecordItem)
end
--TODO 查询战绩
function RecordCtrl.GetRecordByService()
    this.CreateTable(nil)
end
--TODO 根据服务器生成预制体
function RecordCtrl.CreatePrefab()

end
--todo 创建按钮
function RecordCtrl.CreateTable(info)
    this.ReturnBtn=ButtonBase:New(RecordPanel.Return)
    this.ReturnBtn.leftFunc=this.SetFirst
    --清空表,重新计算
    this.AllChildNum=0
    this.RecordTabele={}
    this.RecordInfo={}
    this.AllRecordInfo=info
    ----todo 利用for循环生成按钮
    for i=1,100,1 do
        local obj=objPoolMgr:Get(ObjPoolRecordLeft)
        obj.transform:SetParent(RecordPanel.LeftGrid.transform)
        ---- NGUI的BUG  刷新渲染,不可删除,否则渲染会出问题
        obj.gameObject:SetActive(false)
        obj.gameObject:SetActive(true)
        --生成按钮
        local Btn=ButtonBase:New(obj)
        Btn:SetRight(this.ReturnBtn)
        Btn.PoolName=ObjPoolRecordLeft
        Btn.downFunc=this.DownFunc
        Btn.upFunc=this.UpFunc
        Btn.startFunc=function()
            Btn:SetStartFunc()
            --  todo赋值信息
        end
        table.insert( this.RecordTabele,Btn)
        this.AllChildNum=this.AllChildNum+1
    end
    RecordPanel.LeftGrid:GetComponent("UIGrid"):Reposition()
    this.SetOKFunc()
    --默认第一个值为开始按钮
    this.Index=1
    this.SetFirst()
end
--向下,
function RecordCtrl.DownFunc()
    if this.Index>=this.AllChildNum then
        return nil
    end
    --结束当前按钮的高亮
    this.RecordTabele[this.Index]:SetEnd()
    --表中的下一个按钮为开始按钮
    this.Index=this.Index+1
    --判断位置,战绩一直向下按会导致按钮看不到,所以一定要变换位置
    this.SetPos(mJianGe,mLittlePos)
    --设置按钮高亮
    this.RecordTabele[this.Index]:SetStart()
end
--todo 向上,函数
function RecordCtrl.UpFunc()
    if this.Index<=1 then
        return 0
    end
    this.RecordTabele[this.Index]:SetEnd()
    --表中的上一个按钮为开始按钮
    this.Index=this.Index-1
    this.SetPos(mJianGe,mLittlePos)
    this.RecordTabele[this.Index]:SetStart()
end

-- 设置第一个为开始
function RecordCtrl.SetFirst()
    if this.AllChildNum>0 then
        this.RecordTabele[1]:SetStart()
        local pos=RecordPanel.LeftGrid.localPosition
        RecordPanel.LeftGrid.localPosition=Vector3.New(pos.x,281,pos.z)
    else
        --设置返回按钮高亮
        this.ReturnBtn:SetStart()
    end
    --设置位置
end
--设置ok函数
function RecordCtrl.SetOKFunc()
    this.ReturnBtn.okFunc=function()
        ObjPoolItemName=nil
        RecordLuaBehaviour=nil
        this.Index=0
        this.AllChildNum=0
        this.AllRecordInfo=nil
        this.ReturnBtn=nil
        this.ReleaseObj(this.RecordTabele)
        this.ReleaseObj(this.RecordInfo)
        this.RecordTabele=nil
        this.RecordInfo=nil
        this.Close()
        gameobject=nil
        transform=nil
        --设置大厅高亮按钮
        CtrlManager.GetCtrl(CtrlNames.SignIn).SetFirstBtn()
    end
end
--设置向下位置
function RecordCtrl.SetPos(JianGe,LittlePos)
    local pos=RecordPanel.LeftGrid.localPosition
    --重新赋值,在每隔5和6重新赋值
    local x,y =math.modf(this.Index/6)
    local s,z=math.modf((this.Index-1)/6)
    if y==0 then
        RecordPanel.LeftGrid.localPosition=Vector3.New(pos.x,281+x*LittlePos+s*(6*JianGe-LittlePos),pos.z)
    end
    if z==0 then
        RecordPanel.LeftGrid.localPosition=Vector3.New(pos.x,281+x*LittlePos+s*(6*JianGe-LittlePos),pos.z)
    end
end
--设置向上位置
function RecordCtrl.SetUpPos(JianGe,LittlePos)
    local x,y=math.modf((this.Index-1)/6)
    if y==0 then
        local pos=RecordPanel.LeftGrid.localPosition
        RecordPanel.LeftGrid.localPosition=Vector3.New(pos.x,pos.y-6*JianGe+LittlePos,pos.z)
    end
end

--回收对象池
function RecordCtrl.ReleaseObj(table)
    for i,v in pairs(table) do
        v:ReleaseGo()
    end
end

function RecordCtrl.Close()
    panelMgr:ClosePanel(CloseNames.Record);
end

