---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/24 14:53
---
local gameobject
local transform
SettingCtrl={}
local this=SettingCtrl
function SettingCtrl.New()
    logWarn("SettingCtrl.New--->>");
    return this;
end

function  SettingCtrl.Awake()
    logWarn("SettingCtrl.Awake--->>");
    panelMgr:CreatePanel('Setting', this.OnCreate);
end

function SettingCtrl.OnCreate(obj)
    gameobject=obj
    transform=obj.transform
    ---设置初始ui
    this.InitUI()
    this.CreateBtn()
    this.SetFirstBtn()
end
-- 初始按钮生成  面向对象ButtonBase为所有的基类
function SettingCtrl.CreateBtn()
    --背景音乐
    this.BgBtn=ButtonBase:New(SettingPanel.BgSet)
    --音效
    this.EffectBtn=ButtonBase:New(SettingPanel.EffectSet)
    --返回
    this.ReturnBtn=ButtonBase:New(SettingPanel.Return)
    ----设置左右上下表,
    this.SetTable()
    --设置确定函数
    this.SetSettingBtnOkFun()
end

function SettingCtrl.InitUI()
    local bgValue=soundMgr:GetBgVolum()
    local effectValue=soundMgr:GetEffectVolum()
    --设置初始UI
    if bgValue<=0 then
        SettingPanel.BgStart.gameObject:SetActive(false)
        SettingPanel.BGClose.gameObject:SetActive(true)
    else
        SettingPanel.BGClose.gameObject:SetActive(true)
        SettingPanel.BGClose.gameObject:SetActive(false)
    end
    if effectValue<=0 then
        SettingPanel.EffectStart.gameObject:SetActive(false)
        SettingPanel.EtffecClose.gameObject:SetActive(true)
    else
        SettingPanel.EffectStart.gameObject:SetActive(true)
        SettingPanel.EtffecClose.gameObject:SetActive(false)
    end
end
function SettingCtrl.SetTable()
    this.BgBtn:SetAllTable(nil,nil,nil,this.EffectBtn)
    this.EffectBtn:SetAllTable(nil,nil,this.BgBtn,this.ReturnBtn)
    this.ReturnBtn:SetAllTable(nil,nil,this.EffectBtn,nil)
end

function SettingCtrl.SetSettingBtnOkFun()
    this.BgBtn.okFunc=function()
        soundMgr:SetBgVolum()
        --设置toggle
        SettingPanel.BgStart.gameObject:SetActive(not SettingPanel.BgStart.gameObject.activeSelf)
        SettingPanel.BGClose.gameObject:SetActive(not SettingPanel.BGClose.gameObject.activeSelf)
        this.BgBtn.isReverse=false
    end

    this.EffectBtn.okFunc=function()
        --toggle
        soundMgr:SetEffectVolum()
        SettingPanel.EffectStart.gameObject:SetActive(not SettingPanel.EffectStart.gameObject.activeSelf)
        SettingPanel.EtffecClose.gameObject:SetActive(not SettingPanel.EtffecClose.gameObject.activeSelf)
        this.EffectBtn.isReverse=false
    end

    this.ReturnBtn.okFunc=function()
        this.BgBtn=nil
        this.EffectBtn=nil
        this.ReturnBtn=nil
        this.Close()
        gameobject=nil
        transform=nil
        --在setting可以跳到三个地方,大厅界面,游戏准备阶段,游戏开始阶段
        if currentGameType==1 then
           CtrlManager.GetCtrl(CtrlNames.SignIn).SetFirstBtn()
        else
            CtrlManager.GetCtrl(CtrlNames.Game).SetSettingBtn()
        end
    end
end

function SettingCtrl.SetFirstBtn()
      this.BgBtn:SetStart()
end

--关闭事件--
function SettingCtrl.Close()
    panelMgr:ClosePanel(CloseNames.Setting);
end